# Generated by Django 4.0 on 2022-01-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=64)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('price', models.FloatField(default=0, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.CharField(max_length=32)),
                ('choose', models.ManyToManyField(blank=True, related_name='chooseCategory', to='auctions.Card')),
            ],
        ),
    ]
