# Generated by Django 4.0 on 2022-01-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.AlterField(
            model_name='card',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
