# Generated by Django 4.0 on 2022-01-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_card_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='Title',
            new_name='title',
        ),
    ]
