# Generated by Django 4.0 on 2022-01-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_lot_lot_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='lot_price',
        ),
    ]
