# Generated by Django 4.0 on 2022-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_lot_lot_author_card_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Card'),
        ),
    ]
