# Generated by Django 4.0 on 2022-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_lot_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Category'),
        ),
    ]
