# Generated by Django 4.0 on 2022-01-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_lot_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='lot_category',
        ),
    ]
