# Generated by Django 4.0 on 2022-01-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_lot_lot_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lot_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotname', to='auctions.card'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
