# Generated by Django 4.0 on 2022-01-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_category_lot_title_delete_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status_lot',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
