# Generated by Django 4.0 on 2022-01-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_card_status_lot_alter_card_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_comment', models.TextField(max_length=1000)),
                ('com_pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date published')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercom', to='auctions.user')),
            ],
        ),
    ]
