# Generated by Django 4.0 on 2022-01-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='comment_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CardComment', to='auctions.comment'),
        ),
    ]
