# Generated by Django 4.0 on 2022-01-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_card_comment_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='comment_test',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CardComment', to='auctions.card'),
        ),
    ]
