# Generated by Django 4.0 on 2022-01-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_remove_card_comment_test_comment_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_comment',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='com_pub_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='txt_comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_comment',
            new_name='user',
        ),
    ]
