# Generated by Django 4.0 on 2022-01-12 12:47

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='author',
            field=models.ForeignKey(default=auctions.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='lotAuthor', to='auctions.user'),
        ),
    ]
