# Generated by Django 4.0 on 2022-01-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_alter_comment_user_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status_lot',
            field=models.BooleanField(default=False),
        ),
    ]
