# Generated by Django 4.0 on 2022-01-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_alter_card_status_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status_lot',
            field=models.BooleanField(default=True),
        ),
    ]
