# Generated by Django 4.0 on 2022-01-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watch',
            field=models.ManyToManyField(blank=True, related_name='watch', to='auctions.Card'),
        ),
    ]
