# Generated by Django 4.0 on 2022-01-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_alter_watchlist_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='card',
        ),
    ]
