# Generated by Django 4.0 on 2022-01-14 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_remove_watchlist_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='card',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Cardwatchlist', to='auctions.card'),
            preserve_default=False,
        ),
    ]
