# Generated by Django 4.0 on 2022-01-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_watchlist_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='card',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='watch',
        ),
    ]
