# Generated by Django 4.0 on 2022-01-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_rename_card_watchlist_title_remove_watchlist_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='title',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watch',
            field=models.ManyToManyField(blank=True, related_name='WatchCard', to='auctions.Card'),
        ),
    ]
