# Generated by Django 4.0 on 2022-01-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_rename_lot_watchlist_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watch',
        ),
    ]
