# Generated by Django 4.0 on 2022-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_remove_watchlist_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=64, verbose_name='lot-input'),
        ),
    ]
