# Generated by Django 4.0 on 2022-01-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_alter_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=360),
        ),
    ]
