# Generated by Django 4.0 on 2022-01-17 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.FloatField(default=0, max_length=32, validators=[django.core.validators.RegexValidator(message='Invalid Registration Number', regex='^[1-9]{6}')]),
        ),
    ]
