# Generated by Django 4.0 on 2022-01-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0049_alter_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.FloatField(default=0, max_length=32),
        ),
    ]
