# Generated by Django 4.0 on 2022-01-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_alter_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='price',
            field=models.FloatField(default=1, max_length=6),
        ),
    ]
