# Generated by Django 4.0 on 2022-01-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0053_alter_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='winner',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='lot-winner'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.FloatField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default=None, max_length=24, verbose_name='lot-input'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='rate',
            name='price',
            field=models.FloatField(default=None, max_length=6),
        ),
    ]
