# Generated by Django 4.0 on 2022-01-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0055_alter_card_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='card',
            new_name='title',
        ),
    ]
