# Generated by Django 4.0 on 2022-01-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0056_rename_card_watchlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='close_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='date closed'),
        ),
    ]
