# Generated by Django 4.0 on 2022-01-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0058_alter_category_lot_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='choose',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lot_title',
        ),
    ]
