# Generated by Django 4.0 on 2022-01-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0059_remove_category_choose_remove_category_lot_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='caterogy',
            field=models.ManyToManyField(blank=True, related_name='chooseCategory', to='auctions.Category'),
        ),
    ]
