# Generated by Django 4.0 on 2022-01-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0061_rename_caterogy_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='checked',
            field=models.BooleanField(default=0),
        ),
    ]
